name: "GitHub Deployment's"
description: "GitHub Deployment from GitHub Actions"
author: "Codemonkey51"
inputs:
  status:
    description: "Status for the deployment"
    default: "pending"
    required: false
  update_status:
    description: "Only update the status of a past deploy"
    default: false
    required: false
  deploy_id:
    description: "The status to update (if update_status is set)"
    default: "null"
    required: false
  refrence:
    description: "The reference for the deployment"
    required: false
  token:
    description: "Github access token"
    defualt: ${{ github.secret }}
    required: false
  url:
    description: "Url of deployment"
    required: false
  description:
    description: "Message describing the deployment"
    required: false
  environment_name:
    description: "The evironment name of the deployment"
    default: "production"
    required: false
outputs:
  id:
    description: "The ID of the deployment"
runs:
  using: "node12"
  main: "src/index.js"
